  <?php View::content() ?> 
  <h3>Tabla Tipo de Acceso</h3>
  <!--
  <ul>
     
  <?php foreach($listAcceso->items as $item) : ?> 
  <li>
    <strong><?= $item->id ?> - <?= $item->tipo ?></strong> 
    <?= Html::linkAction("editar/$item->id/", 'Editar') ?> 
    <?= Html::linkAction("eliminar/$item->id/", 'Borrar') ?> 
    <?= Html::linkAction("ver/$item->id/", 'Ver') ?> 
      
  </li>
  <?php endforeach ?>
  </ul>
     !-->
  <table width="70%" border="1px" align="center">

  <tr align="center">

    <td>ID</td>

    <td>Tipo</td>

    <td>Opciones</td>

  </tr>
  <?php foreach($listAcceso->items as $item) : ?> 

  <tr>

    <td><?= $item->id ?></td>

    <td><?= $item->tipo ?></td>

    <td>
    <?= Html::linkAction("editar/$item->id/", 'Editar |') ?> 
    <?= Html::linkAction("eliminar/$item->id/", 'Borrar |') ?> 
    <?= Html::linkAction("ver/$item->id/", 'Ver') ?> 
    </td>

  </tr>
  <?php endforeach ?>

  
</table>


  
   
  <?php if($listAcceso->prev) echo Html::linkAction("index/$listAcceso->prev/", '<< Anterior |') ?> 
  <?php if($listAcceso->next) echo Html::linkAction("index/$listAcceso->next/", 'Proximo >>') ?> 
</div>